# PostgreSQL. Versions 7.4 and 8.x are supported.
#

development:
  adapter: postgresql
  database: kidr_development
  timeout: 5000

test:
  adapter: postgresql
  database: kidr_test
  timeout: 5000

