# PostgreSQL. Versions 7.4 and 8.x are supported.
#

development:
  adapter: postgresql
  database: kidr_development
  timeout: 5000

<<<<<<< HEAD
test:
  adapter: postgresql
=======
test: &test
  adapter: mysql
>>>>>>> c06565924317166a7bbb7c0c6afc6b50351e6b56
  database: kidr_test
  timeout: 5000


cucumber:
  <<: *test
