# PostgreSQL. Versions 7.4 and 8.x are supported.
#

development:
  adapter: mysql
  database: kidr_development
  username: root
  password: root

test: &test
  adapter: mysql
  database: kidr_test
  username: root
  password: root



cucumber:
  <<: *test