# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 35) do

  create_table "admins", :id => false, :force => true do |t|
    t.column "user_id", :integer
  end

  create_table "attachments", :force => true do |t|
    t.column "file", :string
    t.column "description", :string
    t.column "page_id", :integer
  end

  create_table "comments", :force => true do |t|
    t.column "body", :text, :default => "", :null => false
    t.column "author_id", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "page_id", :integer
  end

  create_table "domain_images", :force => true do |t|
    t.column "domain_id", :integer
    t.column "title", :string
    t.column "small", :string
    t.column "large", :string
    t.column "original", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "domain_logos", :force => true do |t|
    t.column "domain_id", :integer
    t.column "small", :string
    t.column "original", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "domains", :force => true do |t|
    t.column "name", :string
    t.column "display_name", :string
    t.column "description", :text
    t.column "google_map_key", :string
    t.column "google_ad_key", :string
    t.column "urchin_account", :string
    t.column "mail_host", :string
    t.column "support_user_name", :string
    t.column "support_password", :string
    t.column "user_id", :integer
    t.column "home_page_my_sites", :boolean
    t.column "home_page_latest_sites", :boolean
    t.column "home_site_search", :boolean
    t.column "home_site_link_to_search", :boolean
    t.column "home_site_link_to_newsite", :boolean
    t.column "byline_link_to_bio", :boolean
    t.column "show_ads", :boolean
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "support_email_address", :string
    t.column "logo", :string
    t.column "create_site_button", :string
    t.column "visible", :boolean, :default => false
    t.column "branding_image", :string
    t.column "stylesheet", :string
  end

  create_table "feedback", :force => true do |t|
    t.column "subject", :string
    t.column "body", :text
    t.column "referrer", :string
    t.column "browser", :string
    t.column "user_id", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "log_entries", :force => true do |t|
    t.column "site_id", :integer
    t.column "page_id", :integer
    t.column "user_id", :integer
    t.column "description", :string
    t.column "created_at", :datetime
  end

  create_table "memberships", :force => true do |t|
    t.column "role_id", :integer
    t.column "site_id", :integer
    t.column "user_id", :integer
  end

  create_table "message_recipients", :force => true do |t|
    t.column "message_id", :integer
    t.column "user_id", :integer
  end

  create_table "messages", :force => true do |t|
    t.column "site_id", :integer
    t.column "user_id", :integer
    t.column "subject", :string
    t.column "body", :text
    t.column "send_at", :datetime
    t.column "sent", :boolean, :default => false, :null => false
    t.column "updated_at", :datetime
    t.column "created_at", :datetime
    t.column "local_send_at", :datetime
  end

  create_table "new_passwords", :force => true do |t|
    t.column "email", :string
    t.column "email_encrypted", :string
    t.column "domain_id", :integer
    t.column "created_at", :datetime
  end

  create_table "pagearchives", :force => true do |t|
    t.column "title", :string, :default => "", :null => false
    t.column "content", :text
    t.column "margin", :text
    t.column "redirect", :string
    t.column "page_id", :integer
    t.column "created_at", :datetime
    t.column "editor_id", :integer
  end

  create_table "pages", :force => true do |t|
    t.column "title", :string, :default => "", :null => false
    t.column "file_name", :string, :default => "", :null => false
    t.column "content", :text
    t.column "position", :integer
    t.column "parent_id", :integer
    t.column "redirect", :string
    t.column "public", :boolean, :default => true
    t.column "visible", :boolean, :default => true
    t.column "site_id", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "last_edited_at", :datetime
    t.column "editor_id", :integer
    t.column "visitor_count", :integer, :default => 0
    t.column "visitor_count_start_at", :datetime
    t.column "comment_level", :string, :default => "none"
    t.column "comments_visible", :boolean, :default => false
    t.column "event_date", :date
    t.column "reminder", :date
    t.column "is_deleted", :boolean, :default => false, :null => false
  end

  create_table "roles", :force => true do |t|
    t.column "name", :string
  end

  create_table "site_images", :force => true do |t|
    t.column "site_id", :integer
    t.column "user_id", :integer
    t.column "title", :string
    t.column "tiny", :string
    t.column "small", :string
    t.column "medium", :string
    t.column "large", :string
    t.column "original", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "sites", :force => true do |t|
    t.column "name", :string
    t.column "logo", :string
    t.column "directory", :string
    t.column "description", :text
    t.column "footer", :text
    t.column "domain_id", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "background_color", :string
    t.column "background_image", :string
    t.column "font_color", :string
    t.column "font_size", :string
    t.column "link_color", :string
    t.column "byline_color", :string
    t.column "font_family", :string
    t.column "nav_border_color", :string
    t.column "nav_background_color", :string
    t.column "nav_background_image", :string
    t.column "nav_font_color", :string
    t.column "nav_link_color", :string
    t.column "open_subscribe", :boolean, :default => false
    t.column "last_edited_at", :datetime
    t.column "content_background_color", :string
    t.column "content_background_image", :string
    t.column "header_background_color", :string
    t.column "logo_font_family", :string
    t.column "logo_font_color", :string
    t.column "under_construction", :boolean, :default => false
    t.column "listed", :boolean, :default => true
    t.column "featured", :boolean, :default => false
    t.column "is_deleted", :boolean, :default => false, :null => false
    t.column "time_zone", :integer, :default => -8
    t.column "subscribe", :integer, :default => 0
    t.column "domain_name", :string
    t.column "stylesheet", :text
    t.column "navigation", :string, :default => "top"
    t.column "mimic_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "email", :string
    t.column "password", :string
    t.column "name", :string
    t.column "bio", :text
    t.column "visitor_code", :string
    t.column "user_type", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "is_deleted", :boolean, :default => false, :null => false
  end

end
